# Generated by Django 5.2.1 on 2025-06-04 13:26

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "item",
                    models.CharField(
                        help_text="The name of the item being ordered", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The cost of the item in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="The number of items being ordered"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="The total cost of the order in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "delivered",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the order has been delivered to us",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Order",
                "verbose_name_plural": "Store Orders",
            },
        ),
    ]
