# Generated by Django 4.1.7 on 2025-06-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_inventory_selling_price"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeorder",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The cost of the item in USD",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="storeorder",
            name="item",
            field=models.ForeignKey(
                help_text="The inventory item being ordered",
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.inventory",
            ),
        ),
    ]
