# Generated by Django 5.2.1 on 2025-06-04 13:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StorePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "item",
                    models.CharField(
                        help_text="The name of the item being purchased", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The cost of the item in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="The number of items being purchased"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="The total cost of the purchase in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="The name of the customer making the purchase",
                        max_length=255,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="The email address of the customer", max_length=254
                    ),
                ),
                (
                    "customer_address",
                    models.CharField(
                        blank=True,
                        default="N/A",
                        help_text="The address of the customer",
                        max_length=255,
                    ),
                ),
                (
                    "sold_by",
                    models.CharField(
                        help_text="The name of the person who sold the item",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Purchase",
                "verbose_name_plural": "Store Purchases",
            },
        ),
        migrations.CreateModel(
            name="OnlinePurchase",
            fields=[
                (
                    "storepurchase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sales.storepurchase",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="The name of the person assigned to handle the online purchase",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Shipping"),
                            ("express", "Express Shipping"),
                            ("pickup", "In-Store Pickup"),
                        ],
                        default="standard",
                        help_text="The method of delivery for the purchase",
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                        ],
                        default="website",
                        help_text="The channel through which the purchase was made",
                        max_length=50,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        help_text="The tracking number for the shipment, if applicable",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "delivered",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the online purchase has been delivered",
                    ),
                ),
            ],
            options={
                "verbose_name": "Online Purchase",
                "verbose_name_plural": "Online Purchases",
            },
            bases=("sales.storepurchase",),
        ),
    ]
