# Generated by Django 4.1.7 on 2025-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_inventory_alter_storepurchase_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The selling price of the item in USD",
                max_digits=10,
            ),
        ),
    ]
