# Generated by Django 4.1.7 on 2025-06-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_customer_remove_storepurchase_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storepurchase",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="The number of items being purchased"
            ),
        ),
    ]
