# Generated by Django 4.1.7 on 2025-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_storepurchase_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storepurchase",
            name="sold_by",
            field=models.CharField(
                blank=True,
                default="N/A",
                help_text="The name of the person who sold the item",
                max_length=255,
            ),
        ),
    ]
